# Generated by Django 4.2 on 2024-02-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payments_transaction_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='product',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='id продукта'),
        ),
    ]
