# Generated by Django 4.2 on 2024-03-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payments_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='payment_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='paid_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='paid_lesson',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='payment_method',
            new_name='method',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='transaction_link',
        ),
        migrations.AddField(
            model_name='payments',
            name='stripe_payment_link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка на оплату Stripe'),
        ),
        migrations.AddField(
            model_name='payments',
            name='stripe_product',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='id продукта Stripe'),
        ),
        migrations.AddField(
            model_name='payments',
            name='stripe_session_id',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='id сессии оплаты Stripe'),
        ),
    ]
