# Generated by Django 4.2 on 2024-02-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='courses', verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='lessons', verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ссылка на видео'),
        ),
    ]
