# Generated by Django 4.2 on 2024-03-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_price',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='id цены Stripe'),
        ),
        migrations.AddField(
            model_name='course',
            name='stripe_product',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='id продукта Stripe'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stripe_price',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='id цены Stripe'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stripe_product',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='id продукта Stripe'),
        ),
    ]
